### ISSUE TITLE
docker-compose.yml multiple services try to bind on local IP port 80

### ISSUE THREAD

**Issue by Krieke** [International-Data-Spaces-Association/IDS-testbed#107]
**Describe the bug**
main:latest
docker-compose.yml multiple services try to bind on local IP port 80
also it would be better that one can view directly within the docker-compose file which IP ports are used by the services. Using expose for inter service communication  or ports which is the same then the latter, with the difference that the port is also exposed outside the docker environment.

**To Reproduce**
1. clone the repository
2. go to the clone directory
3. execute `docker-compose` up
4. when will notice an error that one service can't bind to the local IP port 80 since it is already in use.

**Expected behavior**
All services are bootstrapped without issue

**SUT environment** 
* OS: Ubuntu 20.04 LTS
* Docker: 20.10.21
* Docker-compose: 1.27.4

**Comment by aitorcelaya** [comment]
Hello @Krieke,

I have built the following **SUT environment** to simulate your case as closely as possible:

- OS: Ubuntu 20.04
- Docker: 20.10.17
- Docker-compose: 1.27.4

I have not been able to replicate "port 80 is already in use" with the conditions above.

I would suggest as an initial approach to comment out lines 7 (- 80:80) and 96 (- "81:80") from the ```docker-compose.yml``` file . The pulled ```nginx``` image does use port 80 as well and may be causing a problem on your end.

Let me know if you keep experiencing the same issue.

**Comment by Krieke** [comment]
@aitorcelaya I noticed the port issue both on my Linux and Mac OS environment. Of course I already modified the docker-compose.yml file so that this issue is fixed on my local setup. 

My remark about adapting the docker-compose.yml file in such away that it is clear which ports are being mapped remains, but is not mandatory of course. It is just a proposal for improvements. I am not blocked :-)

**Comment by jfernandezsqs** [comment]
I have been able to replicate this error "multiple services try to bind on local IP port 80" on different Ubuntu OS releases (20.04, 22.04 and 24.04).
The error can be fixed by deleting lines 7 and 141 from the docker-compose.yml file.

It's a good idea to identify the ports to be mapped in the docker-compose so that the user knows which ports to use. If possible it will be generated a PR with the identification of ports used at the docker-compose.yml.

I close this issue as the solution provided fixes the problem of this issue.
