### ISSUE TITLE
Postman collection not running completely anymore

### ISSUE THREAD

**Issue by emilienIMT** [International-Data-Spaces-Association/IDS-testbed#134]
Hello,
I have several instances of the testbed deployed on different environments, and they all have the same issue : for several days, the Postman collection (TestbedPreconfiguration.postman_collection.json) is not running completely anymore.

It fails at the step :` Start Negotiation: POST /api/ids/contract`

I have the issue on our different environments :
* ids-tesbed tag v1.0 and also ids-testbed master branch
* preconfigured setup
* Ubuntu versions : 20.04.6 LTS and Ubuntu 22.04.3 LTS
* Docker Engine versions 24.0.5 and 24.0.6 and 24.0.7
* Docker compose versions 2.20.2 and 2.21.0

![Collection run fails](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/150015173/bb6944a4-1523-48b8-aa8e-657473f87e30)

The export of the run :
[TestBed_Guide.postman_test_run.json](https://github.com/International-Data-Spaces-Association/IDS-testbed/files/13265955/TestBed_Guide.postman_test_run.json)

![log error](https://github.com/International-Data-Spaces-Association/IDS-testbed/assets/150015173/9ecb66dd-f8bd-4b1f-8612-375a8437a936)

The export of the testbed docker compose logs :
[logs.log](https://github.com/International-Data-Spaces-Association/IDS-testbed/files/13266013/logs.log)

Do you have a clue regarding this bug ?

Best regards
Emilien Maudet
Institut Mines Telecom - Teralab

**Comment by emilienIMT** [comment]
The same issue occurs with the exact versions specified in the installation guide :
* Docker 20.10.7 
* Docker-compose 1.27.4
* Ubuntu 20.4

Can you tell me if someone is still receiving/dealing the issues of this repository please ?

**Comment by egonity** [comment]
Hello, i have faced the same problem. The solution is quite simple, we have to update the contract time.
Because in the contract template it is:
{
    "title": "Contract",
    "description": "This is an example contract",
    "provider":"https://connectora:8080/",
    "start": "2021-10-22T07:48:37.068Z",
    "end": "2023-10-22T07:48:37.068Z"
}
The end date must be updated

> The same issue occurs with the exact versions specified in the installation guide :
> 
> * Docker 20.10.7
> * Docker-compose 1.27.4
> * Ubuntu 20.4
> 
> Can you tell me if someone is still receiving/dealing the issues of this repository please ?

**Comment by egonity** [comment]
Hello,  @emilienIMT  i have faced the same problem. The solution is quite simple, we have to update the contract time.
Because in the contract template it is:
{
"title": "Contract",
"description": "This is an example contract",
"provider":"https://connectora:8080/",
"start": "2021-10-22T07:48:37.068Z",
"end": "2023-10-22T07:48:37.068Z"
}
The end date must be updated, and then I think it will work.

**Comment by jfernandezsqs** [comment]
Hello all,
Yes, @egonity the error detailed in this issue is due to the contract generation of the postman collection, which is outdated.
I share at this PR a Postman collection with the contract date fixed.
[TestBed_Guide.postman_collection.json](https://github.com/International-Data-Spaces-Association/IDS-testbed/files/13443484/TestBed_Guide.postman_collection.json)
I have tested it and with this change it works correctly.

The error will be fixed with the next merge performed to the IDS-testbed.

**Comment by emilienIMT** [comment]
Hello !
thank you both for your time !
And thank you for the tip @egonity !
This was the solution indeed.
@jfernandezsqs Maybe the error message (when the contrat is expired) can be a little bit more specific ;)
