### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mohuber** [International-Data-Spaces-Association/IDS-testbed#35]
We should add a license to the testbed repo.
Possibly Apache 2.0?

**Comment by anilturkmayali** [comment]
Hi @mohuber yes Apache 2.0 as mentioned on the (d) of [IDSA IP Policy](https://github.com/International-Data-Spaces-Association/idsa/blob/main/graduation_scheme/IP_Policy.md).

**Comment by Arian-IDSA** [comment]
Thanks @anilturkmayali , 
@mohuber, will it resolve the issue?

**Comment by ssteinbuss** [comment]
Hi all @Arian-IDSA , @anilturkmayali ,
since the repo is public now, we need to add a license to it. Additionally, we need a code of conduct and a contribution file. For the sake of completeness, this also requires a changelog. Therefore, I would propose:

- [ ]  Use the apache 2.0 license or CC-BY 4.0. 
- [ ] Add the Code of conduct based on [contributor covenant](http://contributor-covenant.org/)
- [ ] add a changelog.md and make it mandatory to update it with every PR
- [ ] start using a versioning based on [SemVer](https://semver.org/), Version 1.0.0 would be achieved with the Go live of the certification. 
- [ ] describe the contributions in a contributing-md
- [ ]

**Comment by ssteinbuss** [comment]
Drafted a PR for this. see #36
