### ISSUE TITLE
Error during the install .sh script on Ubuntu VM

### ISSUE THREAD

**Issue by miquinti** [International-Data-Spaces-Association/IDS-testbed#42]
Hi, I'm trying to execute the install.sh script into my Ubuntu server + Docker Virtual Machine, but I'm struggeling with the containers

`ERROR - Omejdn DAPS is not working
ERROR - Dataspace Connector A is not working
ERROR - Dataspace Connector B is not working
ERROR - Metadata Broker is not working
`

Am I missing something in the set up?

Thanks in advance!

**Comment by karikolehmainen** [comment]
Hi, 

I wonder if this is related to https://github.com/International-Data-Spaces-Association/IDS-testbed/issues/39 ? You need to modify the install script in order to run it with out desktop environment.  An other pitfall might be user rights, in order to run docker commands without root privileges you need to create docker group and add right users to it. If you run the script with sudo it might be that the IDS repository path are pointing to root -home directory. Some versions or the gnome-terminal apparently point the working directory to $HOME which would mess up the install script paths.
