### ISSUE TITLE
Using Neuropil as Protocol

### ISSUE THREAD

**Issue by dhommen** [International-Data-Spaces-Association/IDS-testbed#59]
Hi,

since the testbed is required for the certification and we are developing a connector using the [Neuropil](https://gitlab.com/pi-lar/neuropil) protocol for the messages, how can we use the testbed with this protocol?

How do we get certified in this case?

**Comment by aitorce** [comment]
Hi,

I suggest you start with a partial connector integration. The first step is to [register your connector](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/InstallationGuide.md#daps) at the Omejdn DAPS as a client. Have you tried this?

**Comment by Sonia-IDSA** [comment]
Hi @dhommen, 
I brought this issue to the IDSA technical steering committee. There were some discussions with the Neuropil developer last year. We asked him to write the specifications of Neuropil in IDS-G so that they could be reviewed and approved. This way, Neuropil would become an "official" communication protocol. Unfortunately, the specifications aren´t there yet. So a connector that uses Neuropil can´t be certified yet.
BR,
Sonia

**Comment by Sonia-IDSA** [comment]
Topic for the Technical steering committee.
