### ISSUE TITLE
Combining IDS Testbed & MVDS Repositories

### ISSUE THREAD

**Issue by anilturkmayali** [International-Data-Spaces-Association/IDS-testbed#80]
Hello, 

In order to combine IDS Testbed repo with MVDS repository, I created a branch. 

- [Here](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/IDS-testbed-mvds), we have a main page where the initial paragraph explains that testbed can be used for testing and/or as a setup for quickly initiating a data space instance. 

- And a [MVDS.md page](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/IDS-testbed-mvds/minimum-viable-data-space/MVDS.md), that is the same as it was in the MVDS repository. 

Prior to turning this into a pull request I wanted to ask you
1) Whether the main page is good like that? Or should we explain this story in another way?
2) Which parts of the content on the MVDS page should change? What needs to be added/removed/edited.

Could you please comment on that? 

Thank you in advance & all the best!

**Comment by jfernandezsqs** [comment]
Hi @anilturkmayali!
I have the following comments regarding this issue.
First of all, in the folder [minimum-viable-data-space](https://github.com/International-Data-Spaces-Association/IDS-testbed/tree/IDS-testbed-mvds/minimum-viable-data-space) it is not included the images that are specified at the `MVDS.md` file. Because of this, there are two error at the `MVDS.md` file sections [1](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/IDS-testbed-mvds/minimum-viable-data-space/MVDS.md#what-are-the-components-that-make-a-mvds) and [2](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/IDS-testbed-mvds/minimum-viable-data-space/MVDS.md#what-are-the-practical-things-mvds-setup-allows-you-to-do). It is necessary to introduce the `.png` from [here](https://github.com/International-Data-Spaces-Association/idsa/tree/main/MVDS/images) in this folder.

In the file [MVDS](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/IDS-testbed-mvds/minimum-viable-data-space/MVDS.md#what-are-the-components-that-make-a-mvds) I thing it is necessary to introduce a fourth point including the MDB as a component that makes the minimum viable data space.

I believe this [section](https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/IDS-testbed-mvds/minimum-viable-data-space/MVDS.md#what-are-the-practical-things-mvds-setup-allows-you-to-do) should be removed, together with the following two examples.

This [link](https://github.com/International-Data-Spaces-Association/idsa/blob/main/how-to-build-data-spaces/3-Build-Components.md) is not alligned with the purpose of the IDS-testbed. I would remove it from `MVDS.md` file.
This [link](https://github.com/International-Data-Spaces-Association/idsa/tree/main/how-to-build-data-spaces) I believe it is perfect for the IDS-testbed.
